import { describe, it, expect } from 'vitest';
import { gameReducer as reduce, newGame, parseSave, creditFields, type GameState } from '../src/game/engine';
import { CALLERS, DAYS, SCHEMES } from '../src/game/content';
function advance(s: GameState, n: number) { for (let i = 0; i < n; i++) s = reduce(s, { type: 'tick' }); return s; }
function accepted(seed = 123) { return reduce(advance(reduce(newGame(seed), { type: 'start' }), 3), { type: 'accept' }); }
function reveal(s: GameState) { for (let i = 0; i < 3; i++) s = reduce(s, { type: 'reply', tone: CALLERS[s.call!.person].tone }); return s; }
function complete(s: GameState) { s = reveal(s); return reduce(s, { type: 'verify', code: s.call!.code, file: 'mission.txt' }); }
describe('A complete shift', () => {
 it('does not run the clock before clock-in', () => expect(reduce(newGame(), { type: 'tick' }).seconds).toBe(360));
 it('takes an incoming call, builds trust and credits income exactly once', () => { const s = complete(accepted()); expect(s.earned).toBe(250); expect(s.balance).toBe(330); expect(s.successes).toBe(1); expect(reduce(s, { type: 'verify', code: s.call!.code }).earned).toBe(250); });
 it('rejects a correct code until it is revealed through dialogue', () => { const s = accepted(); expect(reduce(s, { type: 'verify', code: s.call!.code }).earned).toBe(0); });
 it('rejects incorrect codes and non-mission remote files', () => { const s = reveal(accepted()); const wrong = reduce(s, { type: 'verify', code: 'fake' }); expect(wrong.earned).toBe(0); expect(wrong.call!.trust).toBe(s.call!.trust - 12); const remote = structuredClone(s); remote.call!.scheme = 'remote'; expect(reduce(remote, { type: 'verify', code: remote.call!.code, file: 'totally-safe.exe' }).earned).toBe(0); expect(reduce(remote, { type: 'verify', code: remote.call!.code, file: 'mission.txt' }).earned).toBe(400); });
 it('ends a call when trust reaches zero', () => { let s = accepted(); for (let i = 0; i < 3; i++) s = reduce(s, { type: 'reply', tone: 'playful' }); expect(s.call).toBeNull(); expect(s.failed).toBe(1); });
 it('expires unanswered calls and active callers', () => { const ringing = advance(reduce(newGame(), { type: 'start' }), 28); expect(ringing.failed).toBe(1); const s = accepted(); const expired = advance(s, s.call!.patience); expect(expired.call).toBeNull(); expect(expired.failed).toBe(1); });
 it('fires a team missing quota and prevents retrying review', () => { const s = reduce(accepted(), { type: 'review' }); expect(s.phase).toBe('fired'); expect(s.history).toHaveLength(1); expect(reduce(s, { type: 'next' })).toEqual(s); expect(reduce(s, { type: 'review' }).history).toHaveLength(1); });
 it('advances a passed day without resetting wallet and upgrades', () => { const base = { ...accepted(), earned: 700, balance: 580, upgrades: ['headset'] }; const s = reduce(reduce(base, { type: 'review' }), { type: 'next' }); expect(s.day).toBe(2); expect(s.phase).toBe('playing'); expect(s.earned).toBe(0); expect(s.balance).toBe(580); expect(s.upgrades).toContain('headset'); });
 it('supports all seven days and the final win state', () => { let s = reduce(newGame(), { type: 'start' }); for (let day = 1; day <= 7; day++) { s.earned = DAYS[day - 1].quota; s = reduce(s, { type: 'review' }); if (day < 7) s = reduce(s, { type: 'next' }); } expect(s.phase).toBe('won'); expect(s.history).toHaveLength(7); });
});
describe('Economy and incidents', () => {
 it('requires all three credit fields in order, rejects bypass and pays only once', () => { let s = accepted(); s.call!.scheme = 'credit'; s = reveal(s); const values = creditFields(s.call!); expect(reduce(s, { type: 'verify', code: s.call!.code }).earned).toBe(0); expect(reduce(s, { type: 'verify-credit', field: 2, value: values[2] })).toEqual(s); const wrong = reduce(s, { type: 'verify-credit', field: 0, value: 'invalid' }); expect(wrong.call!.trust).toBe(s.call!.trust - 12); for (let i = 0; i < 3; i++) { s = reduce(s, { type: 'verify-credit', field: i, value: values[i] }); expect(s.earned).toBe(i === 2 ? 400 : 0); } expect(s.call!.verifiedFields).toBe(3); expect(s.balance).toBe(480); expect(reduce(s, { type: 'verify-credit', field: 2, value: values[2] }).earned).toBe(400); });
 it('preserves actual dialogue and completion status through performance review', () => { const s = complete(accepted()); expect(s.highlights).toHaveLength(3); expect(s.highlights!.every(h => h.success)).toBe(true); const reviewed = reduce(s, { type: 'review' }); expect(reviewed.call).toBeNull(); expect(reviewed.highlights).toEqual(s.highlights); expect(reviewed.highlights![0].trust).toBe(56); });
 it('does not spend daily quota when buying an upgrade, and prevents duplicates', () => { let s = { ...accepted(), balance: 1000, earned: 750 }; s = reduce(s, { type: 'buy', id: 'headset' }); expect(s.balance).toBe(800); expect(s.earned).toBe(750); expect(reduce(s, { type: 'buy', id: 'headset' }).balance).toBe(800); expect(reduce(s, { type: 'buy', id: 'airstrike' }).balance).toBe(800); });
 it('rejects invalid or unaffordable bets; casino winnings do not count as quota', () => { const s = accepted(); for (const bet of [-100, NaN, 100000, 10.5]) expect(reduce(s, { type: 'gamble', bet })).toEqual(s); expect(reduce(s, { type: 'gamble', bet: 10 }).earned).toBe(0); });
 it('triggers and resolves incidents, or prevents them with upgrades', () => { const base = { ...accepted(), day: 2, seconds: 224 }; let s = advance(base, 2); expect(s.event).toBe('virus'); const blocked = reduce(s, { type: 'reply', tone: 'warm' }); expect(blocked.call!.turn).toBe(0); for (let i = 0; i < 3; i++) s = reduce(s, { type: 'fix' }); expect(s.event).toBeNull(); expect(advance({ ...base, upgrades: ['antivirus'] }, 2).event).toBeNull(); });
 it('only offers unlocked business types', () => { let s = reduce(newGame(567), { type: 'start' }); for (let i = 0; i < 20; i++) { s = advance(s, 4); expect(s.call).not.toBeNull(); expect(SCHEMES[s.call!.scheme].day).toBeLessThanOrEqual(s.day); s = reduce(s, { type: 'hangup' }); } });
});
describe('Save compatibility and validation', () => {
 it('roundtrips a live call including large PRNG state', () => { const s = reveal(accepted(3000000000)); expect(parseSave(JSON.parse(JSON.stringify(s)))).toEqual(s); });
 it('rejects corrupted, unknown and non-finite values', () => { const s = newGame(); expect(parseSave({ ...s, version: 9 })).toBeNull(); expect(parseSave({ ...s, day: 8 })).toBeNull(); expect(parseSave({ ...s, balance: Infinity })).toBeNull(); expect(parseSave({ ...s, upgrades: ['cheat'] })).toBeNull(); expect(parseSave({ ...s, history: [null] })).toBeNull(); expect(parseSave({ ...accepted(), call: { person: 999 } })).toBeNull(); expect(parseSave(null)).toBeNull(); });
 it('migrates older saves and rejects corrupt credit steps or replay data', () => { expect(parseSave(newGame())?.highlights).toEqual([]); const s = accepted(); expect(parseSave({ ...s, call: { ...s.call, verifiedFields: 4 } })).toBeNull(); expect(parseSave({ ...s, highlights: [{ quote: 'bad' }] })).toBeNull(); });
 it('does not mutate previous state', () => { const s = accepted(); const before = JSON.stringify(s); reduce(s, { type: 'reply', tone: 'warm' }); expect(JSON.stringify(s)).toBe(before); });
});
