import { describe, expect, it, vi } from 'vitest';
import { gameReducer as reduce, newGame, applyDialogue, parseSave, type GameState } from '../src/game/engine';
import { addActor, distance, EMPTY_INPUT, interactWorld, isWalkable, makeWorld, SEATS, setInput, STATIONS, stepWorld, syncDeliveries } from '../src/game/world';
import { generateDialogue } from '../worker/dialogue';
import { iceConfiguration } from '../worker/rtc';
import type { Env } from '../worker/auth';

function tick(state: GameState, n = 1) { for (let i = 0; i < n; i++) state = reduce(state, { type: 'tick' }); return state; }
function playing() { return reduce(newGame(42), { type: 'start' }); }
function call() { return reduce(tick(playing(), 3), { type: 'accept' }); }
function office() { const w = makeWorld(); addActor(w, 'a', 'Alice', 0); addActor(w, 'b', 'Bob', 1); return w; }

describe('Walkable shared office', () => {
 it('accepts input, rejects teleport payloads and replayed or malformed movement', () => { const w = office(); const start = w.actors.a.z; expect(setInput(w, 'a', { ...EMPTY_INPUT, seq: 1, forward: 1, x: 1000 })).toBe(true); stepWorld(w, .2); expect(w.actors.a.z).toBeCloseTo(start - .62); expect(w.actors.a.x).toBeCloseTo(-4.8); expect(setInput(w, 'a', { ...EMPTY_INPUT, seq: 1 })).toBe(false); expect(setInput(w, 'a', { ...EMPTY_INPUT, seq: 2, forward: 2 })).toBe(false); expect(setInput(w, 'a', { ...EMPTY_INPUT, seq: 2, yaw: NaN })).toBe(false); });
 it('normalizes diagonal speed and stops when packets stop arriving', () => { const w = office(); const p = w.actors.a; p.x = 0; p.z = 7; const start = { ...p }; setInput(w, 'a', { ...EMPTY_INPUT, seq: 1, forward: 1, side: 1 }); stepWorld(w, .2); expect(distance(p, start)).toBeCloseTo(.62); stepWorld(w, .3); const stopped = { ...p }; stepWorld(w, .3); expect(p.x).toBe(stopped.x); expect(p.z).toBe(stopped.z); });
 it('blocks desks and outer walls while preserving paths to both extra rooms', () => { expect(isWalkable(-4.8, 3.2)).toBe(false); expect(isWalkable(-9, 0)).toBe(false); expect(isWalkable(21, 0)).toBe(false); for (const [x, z] of [[.5, 6],[8.5, 5.7],[10, 0],[12, 0],[12, -4],[18.8, -5.4],[12, 5],[18, 7]]) expect(isWalkable(x, z)).toBe(true); const w = office(); const p = w.actors.a; for (let seq = 1; seq <= 15; seq++) { setInput(w, 'a', { ...EMPTY_INPUT, seq, forward: 1 }); stepWorld(w, .2); } expect(p.z).toBeGreaterThanOrEqual(4.28); expect(isWalkable(p.x, p.z)).toBe(true); });
 it('requires proximity to the personal seat and keeps seated actors stationary', () => { const w = office(), g = playing(); expect(interactWorld(w, 'a', { type: 'sit' }, g).message).toContain('工位'); Object.assign(w.actors.a, { x: SEATS[1].x, z: 5 }); interactWorld(w, 'a', { type: 'sit' }, g); expect(w.actors.a.mode).toBe('standing'); Object.assign(w.actors.a, { x: SEATS[0].x, z: 5.1 }); interactWorld(w, 'a', { type: 'sit' }, g); setInput(w, 'a', { ...EMPTY_INPUT, seq: 1, forward: 1 }); stepWorld(w, .2); expect(w.actors.a.mode).toBe('seated'); expect(w.actors.a.z).toBe(SEATS[0].z); interactWorld(w, 'a', { type: 'stand' }, g); expect(isWalkable(w.actors.a.x, w.actors.a.z)).toBe(true); });
 it('uses one authoritative body for pickup, throw, gravity and player impacts', () => { const w = office(), g = playing(), p = w.actors.a; Object.assign(p, { x: .7, z: 6.2 }); interactWorld(w, 'a', { type: 'interact' }, g); const b = w.bodies.find(b => b.id === p.held)!; expect(b.heldBy).toBe('a'); stepWorld(w, .1); interactWorld(w, 'a', { type: 'throw' }, g); expect(b.heldBy).toBeNull(); const before = b.z; stepWorld(w, .1); expect(b.z).toBeLessThan(before); Object.assign(b, { x: 0, z: 7, y: 1, vx: 0, vz: 6, vy: 0 }); Object.assign(w.actors.b, { x: 0, z: 7.4 }); stepWorld(w, .04); expect(w.actors.b.stun).toBeGreaterThan(0); for (let i = 0; i < 80; i++) stepWorld(w, .2); expect(b.y).toBeGreaterThanOrEqual(b.radius); });
 it('spends stamina, jumps, and cancels movement during stun', () => { const w = office(), p = w.actors.a; setInput(w, 'a', { ...EMPTY_INPUT, forward: 1, sprint: true, jump: true, seq: 1 }); stepWorld(w, .1); expect(p.stamina).toBeLessThan(92); expect(p.y).toBeGreaterThan(0); p.stun = 1; const z = p.z; stepWorld(w, .1); expect(p.z).toBe(z); });
});

describe('Economy, delivery and item effects', () => {
 it('debits wallet without spending quota, then delivers, claims and installs exactly once', () => { let g = { ...playing(), balance: 1000, earned: 750 }; const w = office(); g = reduce(g, { type: 'buy', id: 'headset' }); expect(g.balance).toBe(800); expect(g.earned).toBe(750); expect(g.upgrades).not.toContain('headset'); expect(g.inventory?.headset).toBeUndefined(); expect(reduce(g, { type: 'claim', id: 1 })).toBe(g); g = tick(g, 5); syncDeliveries(w, 'a', g); expect(w.bodies.filter(b => b.kind === 'parcel')).toHaveLength(1); Object.assign(w.actors.a, { x: 6, z: 7 }); g = interactWorld(w, 'a', { type: 'interact' }, g).game; expect(g.inventory?.headset).toBe(1); expect(w.bodies.some(b => b.kind === 'parcel')).toBe(false); g = interactWorld(w, 'a', { type: 'use', item: 'headset' }, g).game; expect(g.upgrades).toContain('headset'); expect(g.inventory?.headset).toBe(0); expect(reduce(g, { type: 'buy', id: 'headset' })).toBe(g); expect(g.ledger?.[0].amount).toBe(-200); expect(g.achievements).toContain('buyer'); expect(parseSave(g)).toEqual(g); });
 it('keeps parcels private and allows consumable repeat orders', () => { const w = office(); let g = { ...playing(), balance: 1000 }; g = reduce(reduce(g, { type: 'buy', id: 'energy' }), { type: 'buy', id: 'energy' }); g = tick(g, 5); syncDeliveries(w, 'a', g); Object.assign(w.actors.b, { x: 6, z: 7.4 }); interactWorld(w, 'b', { type: 'interact' }, playing()); expect(w.bodies.filter(b => b.kind === 'parcel')).toHaveLength(2); expect(g.balance).toBe(880); });
 it('consumes repair only at the failed power station and energy restores stamina and patience', () => { const w = office(); const g = { ...call(), event: 'power' }; expect(interactWorld(w, 'a', { type: 'use', item: 'repair' }, g).game).toBe(g); Object.assign(w.actors.a, STATIONS.power); const repaired = interactWorld(w, 'a', { type: 'use', item: 'repair' }, g).game; expect(repaired.event).toBeNull(); expect(repaired.inventory?.repair).toBe(0); w.actors.a.stamina = 5; const energy = interactWorld(w, 'a', { type: 'use', item: 'energy' }, repaired).game; expect(w.actors.a.stamina).toBe(100); expect(energy.call!.patience).toBe(repaired.call!.patience + 25); });
 it('extinguisher resolves fire, shield is consumed by raid, and confetti changes physics', () => { const g = { ...playing(), event: 'fire', inventory: { extinguisher: 1, airstrike: 1 } }; const after = reduce(g, { type: 'use-item', id: 'extinguisher' }); expect(after.event).toBeNull(); const raid = tick({ ...after, day: 5, seconds: 223, upgrades: ['shield'] }); expect(raid.event).toBeNull(); expect(raid.upgrades).not.toContain('shield'); const w = office(); Object.assign(w.actors.a, { x: .7, z: 5.5 }); const burst = interactWorld(w, 'a', { type: 'use', item: 'airstrike' }, after); expect(burst.game.inventory?.airstrike).toBe(0); expect(w.burst).not.toBeNull(); expect(w.bodies[0].vy).toBe(7); expect(w.actors.a.stun).toBe(2); });
 it('rejects duplicated shipment ids, unknown stock and invalid counters in saves', () => { const g = playing(); expect(parseSave({ ...g, streak: -1 })).toBeNull(); expect(parseSave({ ...g, inventory: { money: 999 } })).toBeNull(); expect(parseSave({ ...g, orderSerial: 1, deliveries: [{ id: 1, item: 'energy', seconds: 0 }, { id: 1, item: 'energy', seconds: 0 }] })).toBeNull(); });
});

describe('Actual provider contracts and deterministic game authority', () => {
 it('sends structured AI requests and never grants money from model output', async () => { const g = call(); const fetcher = vi.fn(async (_url: unknown, init?: RequestInit) => { const body = JSON.parse(String(init?.body)); expect(body.response_format.json_schema.strict).toBe(true); expect(body.model).toBe('test/provider'); expect(JSON.parse(body.messages.at(-1).content.split('\n').slice(1).join('\n'))).toMatchObject({ current_speaker: 'you', current_reply: '我在听', output_speaker: 'caller' }); return Response.json({ choices: [{ message: { content: JSON.stringify({ reply: '谢谢你愿意听我说。', attitude: 'positive', money: 999999 }) } }] }); }) as unknown as typeof fetch; const result = await generateDialogue({ OPENROUTER_API_KEY: 'server-only-key', AI_MODEL: 'test/provider' } as Env, g.call!, '我在听', fetcher); const next = applyDialogue(g, '我在听', result); expect(next.call!.trust).toBe(56); expect(next.balance).toBe(80); expect(next.earned).toBe(0); expect(next.call!.revision).toBe(1); expect(applyDialogue(next, '重复提交', result)).toBe(next); });
 it('rejects stale responses even after the transcript reaches its size limit', () => { let g = call(); for (let i = 0; i < 15; i++) g = applyDialogue(g, '继续', { callCode: g.call!.code, callId: g.call!.id, turn: g.call!.revision || 0, attitude: 'neutral', reply: '我还在考虑。' }); expect(g.call!.transcript).toHaveLength(20); const old = { callCode: g.call!.code, callId: g.call!.id, turn: g.call!.revision || 0, attitude: 'positive' as const, reply: '好的。' }; g = applyDialogue(g, '第一次', old); expect(applyDialogue(g, '过期的第二次', old)).toBe(g); expect(applyDialogue(g, '错误通话', { ...old, turn: g.call!.revision!, callCode: 'OTHER' })).toBe(g); });
 it('reveals canonical game codes after valid AI turns and ignores replies after hangup', () => { let g = call(); for (let i = 0; i < 3; i++) g = applyDialogue(g, '耐心回应', { callCode: g.call!.code, callId: g.call!.id, turn: g.call!.revision || 0, attitude: 'positive', reply: '这样就说得通了。' }); expect(g.call!.revealed).toBe(true); expect(g.call!.transcript.at(-1)!.text).toContain(g.call!.code); const result = { callCode: g.call!.code, callId: g.call!.id, turn: g.call!.revision!, attitude: 'positive' as const, reply: '迟到的回答' }; g = reduce(g, { type: 'hangup' }); expect(applyDialogue(g, '你好', result)).toBe(g); });
 it('surfaces unconfigured, invalid and rejected AI providers', async () => { const c = call().call!; await expect(generateDialogue({} as Env, c, 'hi')).rejects.toThrow('尚未配置'); const env = { AI_API_KEY: 'secret', AI_MODEL: 'test' } as Env; await expect(generateDialogue(env, c, 'hi', (async () => new Response('', { status: 401 })) as typeof fetch)).rejects.toThrow('鉴权'); await expect(generateDialogue(env, c, 'hi', (async () => Response.json({ choices: [{ message: { content: 'not json' } }] })) as typeof fetch)).rejects.toThrow('格式'); });
 it('provides STUN without TURN and exchanges server secret for short-lived relay credentials', async () => { expect((await iceConfiguration({} as Env)).relay).toBe(false); const fetcher = vi.fn(async (url: unknown, init?: RequestInit) => { expect(String(url)).toContain('/turn/keys/test-key/credentials/generate-ice-servers'); expect(JSON.parse(String(init?.body)).ttl).toBe(7200); expect((init?.headers as Record<string, string>).Authorization).toBe('Bearer server-secret'); return Response.json({ iceServers: [{ urls: ['turn:relay.example:3478'], username: 'temp', credential: 'short-lived' }] }); }) as unknown as typeof fetch; const config = await iceConfiguration({ TURN_KEY_ID: 'test-key', TURN_API_TOKEN: 'server-secret' } as Env, fetcher); expect(config.relay).toBe(true); expect(JSON.stringify(config)).not.toContain('server-secret'); });
});
