import {getLocale,languageTags} from '../i18n';
import {t} from '../i18n';
import { useState } from 'react';
import { ACHIEVEMENTS, CALLERS, DAYS, SCHEMES, SHOP } from '../game/content';
import type { GameState } from '../game/engine';
import type { WorldCommand } from '../game/world';
import type { VoiceClient } from '../game/useVoice';
import type { RoomSnapshot } from '../game/useRoom';
import { Icon } from './Icon';
import { Portrait } from './Portrait';
export function InventoryApp({ game, use, leaveDesk }: { game: GameState; use: (c: WorldCommand) => void; leaveDesk: () => void }) {
 return <div className="inventory-app"><header><Icon name="folder" size={32}/><div><h2>{t("我的背包")}</h2><p>{t("实物需要到办公室收货区拆封。安装与使用后才生效。")}</p></div></header>{!!game.deliveries?.length && <section><h3>{t("配送中的订单")}</h3>{game.deliveries.map(d => <div className="inventory-order" key={d.id}><span>{SHOP.find(s => s.id === d.item)?.name}</span><b>{t(d.seconds ? `${d.seconds}s 后送达` : '收货区待领取')}</b></div>)}<button className="yellow" onClick={leaveDesk}>{t("离开工位，去收货区")}</button></section>}<div className="inventory-grid">{SHOP.filter(item => (game.inventory?.[item.id] || 0) > 0).map(item => <article key={item.id}><Icon name={item.icon} size={30}/><h3>{t(item.name)}<span>×{t(game.inventory![item.id])}</span></h3><p>{t(item.description)}</p><button className="blue" disabled={game.phase !== 'playing'} onClick={() => use({ type: 'use', item: item.id })}>{t(item.repeatable ? '使用' : '安装 / 装备')}</button></article>)}</div>{!Object.values(game.inventory || {}).some(n => n > 0) && <p className="empty-backpack">{t("背包空空。去 Scamazon 购买补给，或等待包裹到达。")}</p>}<section><h3>{t("已安装 / 已装备")}</h3><div className="equipment-tags">{game.upgrades.map(id => <span key={id}><Icon name={SHOP.find(x => x.id === id)?.icon || 'check'} size={14}/>{SHOP.find(x => x.id === id)?.name}</span>)}{!game.upgrades.length && <small>{t("暂无装备。")}</small>}</div></section></div>;
}
export function LedgerApp({ game }: { game: GameState }) { return <div className="ledger-app"><small>{t("KOLKATA FINANCE · AUDIT TRAIL")}</small><h2>{t("每一笔钱，都有去处。")}</h2><div className="ledger-summary"><span>{t("个人钱包")}<b>${t(game.balance.toLocaleString(languageTags[getLocale()]))}</b></span><span>{t("今日业绩")}<b>${t(game.earned.toLocaleString(languageTags[getLocale()]))}</b></span><span>{t("累计业务收入")}<b>${t(game.lifetime.toLocaleString(languageTags[getLocale()]))}</b></span></div><p>{t("业务完成同时增加钱包与业绩；购物与娱乐只改变钱包。游戏币只用于本游戏。")}</p><section><h3>{t("最近交易")}</h3>{(game.ledger || []).map((l, i) => <div className="ledger-row" key={i}><span><b>{t(l.label)}</b><small>{t("DAY {0} · 余额 ${1}", [l.day, l.balance.toLocaleString(languageTags[getLocale()])])}</small></span><strong className={l.amount >= 0 ? 'success-text' : 'danger-text'}>{t(l.amount >= 0 ? '+' : '−')}${t(Math.abs(l.amount).toLocaleString(languageTags[getLocale()]))}</strong></div>)}{!game.ledger?.length && <p>{t("入职补助 $80 已放入钱包。完成首笔业务后会生成流水。")}</p>}</section><section><h3>{t("员工成就 · {0}/{1}", [game.achievements?.length || 0, ACHIEVEMENTS.length])}</h3><div className="achievement-grid">{ACHIEVEMENTS.map(a => <div className={game.achievements?.includes(a.id) ? 'unlocked' : ''} key={a.id}><Icon name={game.achievements?.includes(a.id) ? 'prize' : 'lock'} size={20}/><b>{t(a.name)}</b><small>{t(a.description)}</small></div>)}</div></section></div>; }
export function CustomerApp({ game }: { game: GameState }) { const [person, setPerson] = useState(game.call?.person || 0); const p = CALLERS[person]; return <div className="customer-app"><header><h2>{t("Caller Records")}</h2><small>{t("虚构人物档案 · 第三天解锁")}</small></header>{game.day < 3 ? <div className="locked-dossier"><Icon name="lock" size={40}/><h3>{t("完成第二天考核后开放")}</h3><p>{t("档案可帮助你了解人物偏好和历史成交情况。")}</p></div> : <><nav>{CALLERS.map((p, i) => <button className={person === i ? 'selected' : ''} key={p.name} onClick={() => setPerson(i)}>{t(p.name.split(' ')[0])}</button>)}</nav><section><Portrait person={person}/><h2>{p.name}</h2><p>{t(p.role)}</p><dl><dt>{t("对话偏好")}</dt><dd>{t(p.tone === 'warm' ? '耐心倾听与尊重' : p.tone === 'confident' ? '明确步骤与可靠的说明' : '轻松自然的幽默')}</dd><dt>{t("已记录通话")}</dt><dd>{new Set((game.highlights || []).filter(h => h.person === person).map(h => h.callId)).size} {t(" 次")}</dd><dt>{t("最近说过")}</dt><dd>{(game.highlights || []).filter(h => h.person === person).at(-1)?.response || p.intro}</dd></dl></section></>}</div>; }
export function VoicePanel({ voice, room }: { voice: VoiceClient; room: RoomSnapshot | null }) { return <div className="voice-panel"><header><Icon name="headphones" size={30}/><div><h2>{t("办公室语音")}</h2><p>{t("真人同事通话 · {0}", [room ? `房间 ${room.code}` : '加入多人办公室后可用'])}</p></div></header>{!room ? <p>{t("先通过主菜单创建或加入办公室，再开启麦克风。")}</p> : <><button className={voice.enabled ? 'red full' : 'green full'} disabled={voice.busy} onClick={() => voice.enabled ? voice.stop() : void voice.start()}><Icon name={voice.enabled ? 'micOff' : 'mic'} size={18}/>{t(voice.busy ? '正在连接麦克风…' : voice.enabled ? '退出真人语音' : '开启麦克风并加入语音')}</button>{voice.enabled && <><button className={`push-to-talk ${voice.pressed ? 'transmitting' : ''}`} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); voice.updateMic(true); }} onPointerUp={() => voice.updateMic(false)} onPointerCancel={() => voice.updateMic(false)}><Icon name="mic"/>{t("按住说话 ")}<kbd>{t("V")}</kbd><i style={{ width: `${voice.level * 100}%` }}/></button><label className="voice-option"><input type="checkbox" checked={voice.openMic} onChange={e => voice.setOpenMic(e.target.checked)}/>{t("持续开麦")}</label><label className="voice-option"><input type="checkbox" checked={voice.proximity} onChange={e => voice.setProximity(e.target.checked)}/>{t("距离越远，声音越小")}</label><small>{t(voice.relay ? '已配置 Cloudflare TURN 中继' : '直连模式；跨网络无法连接时需要配置 TURN')}</small><button onClick={voice.resume}>{t("恢复声音")}</button></>}<div className="voice-peers">{room.players.map(p => <div key={p.id}><span className={p.voice ? 'online-dot' : 'offline-dot'}/><b>{p.name}</b><small>{t(p.id === room.self ? voice.enabled ? '自己 · 已加入' : '自己 · 麦克风关闭' : !p.online ? '离线' : !p.voice ? '未加入语音' : voice.connections[p.id] === 'connected' ? '语音已连接' : voice.connections[p.id] || '等待连接')}</small></div>)}</div></>}{voice.error && <p className="form-error" role="alert">{t(voice.error)}</p>}</div>; }
export function GameplayApp() { return <div className="gameplay-app"><small>{t("EMPLOYEE HANDBOOK · WEB EDITION")}</small><h2>{t("从第一通电话，")}<br/>{t("到整个办公室。")}</h2><p>{t("每天的目标是和同事一起完成业绩。你可以离开座位收包裹、处理停电、使用道具，再回到自己的电脑继续工作。")}</p><section><h3>{t("01 · 行动与入座")}</h3><p>{t("WASD 移动，Shift 奔跑，Space 跳跃，拖动鼠标环顾或锁定鼠标。C 切换第一 / 第三人称。靠近黄色标记的个人工位按 E 入座；Tab 离席。办公室右侧通道连接茶水间与考核会议室。")}</p></section><section><h3>{t("02 · 完成业务")}</h3><p>{t("接听来电，用启用 AI 后的自由文字、语音输入或建议应答交流。AI 模式会理解语境；离线模式根据人物偏好回应。建立信任后取得游戏标记，交给对应应用验证。信任归零或耐心耗尽会挂断，任务不能重复结算。")}</p><div className="business-list">{Object.values(SCHEMES).map(s => <div key={s.title}><b>{t(s.title)}</b><span>{t("第 {0} 天 · ${1}", [s.day, s.payout])}</span><small>{t(s.description)}</small></div>)}</div></section><section><h3>{t("03 · 钱包、配送与道具")}</h3><p>{t("每次成交同时增加个人钱包和团队业绩；购物不会扣减已完成的业绩。软件立即安装，实物 5 秒后到办公室右后方收货区。靠近自己的包裹按 E 拆封，I 打开背包。永久升级生效于之后的通话；消耗品用完需要补货。")}</p></section><section><h3>{t("04 · 事故与物理交互")}</h3><p>{t("病毒用 Malwarebits 清理；停电到茶水间配电箱按 E 分三步恢复，或使用维修包；火灾可用灭火器；防暴盾抵挡下一次突袭后消耗。地面的物品可按 E 拿起，左键投掷，Q 放下。高速物体会使同事短暂踉跄。")}</p></section><section><h3>{t("05 · 和同事合作")}</h3><p>{t("1–4 人共享工作日与总业绩，每人有自己的工位、来电、钱包和背包。位置、坐席和道具由房间服务同步。打开真人语音后按住 V 说话；距离音量可在语音应用里关闭。房主可提前考核或进入下一天。")}</p></section><section><h3>{t("06 · 复盘与成长")}</h3><p>{t("七天目标逐步提高，完成考核保留钱包与装备。财务应用记录交易和成就；第三天开放客户档案；考核会议室提供真实通话复盘和朗读。娱乐收益不计入业绩，未达标会结束本轮。失败会增加风险，风险每升高 4 点，之后来电的耐心减少 1 秒；绿植与故障处理可降低风险。")}</p></section><section><h3>{t("07 · 道具说明与购买选择")}</h3><p>{t("入职赠送一瓶能量饮料和一个维修包。降噪耳机适合先建立信任，绩效放大器提高每笔收入；收入再高也需要及时提交对应业务验证。")}</p><div className="business-list">{SHOP.map(item => <div key={item.id}><b>{t(item.name)}</b><span>${t(item.price)} · {t(item.delivery ? '实物配送' : '即刻安装')}</span><small>{t(item.description)}</small></div>)}</div></section><section><h3>{t("08 · 七天挑战")}</h3><div className="business-list">{DAYS.map((day,i) => <div key={day.name}><b>{t("DAY {0} · {1}", [i+1, day.name])}</b><span>{t("目标 ${0} · {1} 分钟", [day.quota, day.seconds/60])}</span><small>{t(day.brief)}</small></div>)}</div></section></div>; }
