import {t} from '../i18n';
import { useState } from 'react';
import { SCHEMES, type Scheme } from '../game/content';
import type { Action, GameState } from '../game/engine';
import { Icon } from './Icon';
export function ToolApp({ id, game, dispatch }: { id: Scheme; game: GameState; dispatch: (a: Action) => void }) {
 const [code, setCode] = useState(''); const [connected, setConnected] = useState(false); const [file, setFile] = useState(''); const [error, setError] = useState(''); const scheme = SCHEMES[id]; const c = game.call; const available = c?.scheme === id && c.status !== 'ringing'; const done = available && c.status === 'complete';
 if (id === 'credit') return <CreditApp game={game} dispatch={dispatch}/>;
 const submit = () => { if (!available) { setError('请先接听对应业务的来电。'); return; } if (id === 'remote' && !connected) { if (c.revealed && code.trim().toUpperCase() === c.code) { setConnected(true); setError(''); } else setError('连接编号不匹配，请检查通话记录。'); return; } if (id === 'remote' && !file) { setError('请选中任务文件。'); return; } dispatch({ type: 'verify', code, file }); };
 return <div className={`tool-app ${id}`}><header className="tool-heading"><span><Icon name={id} size={30}/></span><div><h2>{t(id === 'identity' ? 'Social Security Stealer' : scheme.title)}</h2><p>{t(id === 'identity' ? '模拟身份档案验证终端' : scheme.name)}</p></div><b>{t("KOS")}<br/>{t("APP")}</b></header>
 <div className="tool-inner"><div className={`tool-notice ${done ? 'success' : ''}`}><Icon name={done ? 'check' : 'lock'} size={16}/>{t(done ? `Scam complete — $${Math.round(scheme.payout * (game.upgrades.includes('bonus') ? 1.2 : 1))} earned.` : `任务报酬 $${scheme.payout} · ${available ? '来电已连接' : '等待对应业务来电'}`)}</div>
 {connected && id === 'remote' ? <div className="remote-desktop"><div className="remote-bar"><span>{t("REMOTE SESSION · 模拟电脑")}</span><i>{t("● 已连接")}</i></div><div className="remote-files">{['holiday.jpg', 'mission.txt', 'totally-safe.exe'].map(name => <button key={name} className={file === name ? 'selected' : ''} onClick={() => { setFile(name); if (name.endsWith('exe')) setError('可疑程序！需要的是 .txt 任务文件。'); else setError(''); }}><Icon name={name.endsWith('txt') ? 'file' : name.endsWith('exe') ? 'warning' : 'folder'} size={38}/><span>{t(name)}</span></button>)}</div><p>{t("任务：找到名为 mission.txt 的文件并完成验证。")}</p></div> : <><p className="tool-description">{t(scheme.description)}</p><label className="field-label">{t(id === 'remote' ? 'Caller’s connection code' : '虚构任务编号 / Mission ID')}<input autoComplete="off" spellCheck={false} placeholder={t(`GAME-${scheme.code}-XXX`)} aria-label={t(`${scheme.title} 任务编号`)} value={code} onChange={e => { setCode(e.target.value); setError(''); }} onKeyDown={e => { if (e.key === 'Enter') submit(); }} disabled={done}/></label><div className="tool-help"><Icon name="help" size={15}/><span>{t("先通过对话取得编号，再将它填入此处。")}<br/>{t("所有编号均由游戏生成。")}</span></div></>}
 {error && <p className="form-error" role="alert">{t(error)}</p>}<div className="tool-bottom"><span>{t(done ? 'Verified ✓' : available ? '● Call connected' : '○ No active call')}</span><button className={id === 'remote' ? 'red' : 'blue'} disabled={done || !!game.event || !code.trim()} onClick={submit}>{t(done ? '已验证' : id === 'remote' && !connected ? 'Connect' : 'Verify')}<Icon name={done ? 'check' : 'right'} size={15}/></button></div></div>
 <footer>{t("FICTIONAL DATA ONLY ")}<span>{t("Kolkata Business Suite © 2026")}</span></footer></div>;
}
function CreditApp({ game, dispatch }: { game: GameState; dispatch: (a: Action) => void }) {
 const [values, setValues] = useState(['', '', '']); const c = game.call; const active = c?.scheme === 'credit' && c.status === 'active'; const done = c?.scheme === 'credit' && c.status === 'complete'; const step = c?.scheme === 'credit' ? c.verifiedFields || 0 : 0;
 return <div className="tool-app credit"><header className="tool-heading"><span><Icon name="credit" size={30}/></span><div><h2>{t("Credit Card Record")}</h2><p>{t("卡片资料 · 分步验证终端")}</p></div></header><div className="tool-inner"><div className={`tool-notice ${done ? 'success' : ''}`}><Icon name={done ? 'check' : 'lock'} size={16}/>{t(done ? `Scam complete — $${game.upgrades.includes('bonus') ? 480 : 400} earned.` : `$400 · ${step}/3 VERIFIED`)}</div><p className="tool-description">{t("从通话记录中找到这张游戏卡片的三个信息。依次验证，全部通过后到账。")}</p><div className="card-preview"><Icon name="credit" size={27}/><span>{t("KOLKATA PLAY CARD")}</span><strong>{t("GAME •••• ••••")}</strong><small>{t("OFFICE USE ONLY")}</small></div>{['游戏卡号 / Card ID', '安全口令 / Security', '到期标记 / Expiry'].map((label, i) => <form className={`credit-field ${i < step ? 'verified' : ''}`} key={label} onSubmit={e => { e.preventDefault(); dispatch({ type: 'verify-credit', field: i, value: values[i] }); }}><label>{t(label)}<input aria-label={t(label)} autoComplete="off" spellCheck={false} value={values[i]} placeholder={t(['GAME-CARD-XXX', 'PIX-XXX', 'MOON-XX'][i])} disabled={!active || i !== step} onChange={e => setValues(v => v.map((x, j) => j === i ? e.target.value : x))}/></label><button className={i < step ? 'green' : 'blue'} disabled={!active || i !== step || !values[i].trim() || !!game.event}>{i < step ? <Icon name="check" size={16}/> : t('Verify')}</button></form>)}<div className="tool-help"><Icon name="help" size={15}/><span>{t("单击通话中的卡号、安全口令或到期标记即可全选，复制后粘贴到对应输入框。")}</span></div></div><footer>{t("FICTIONAL DATA ONLY ")}<span>{t("Kolkata Business Suite")}</span></footer></div>;
}
