import {getLocale,languageTags} from '../i18n';
import {t} from '../i18n';
import { useRef, useState, type PointerEvent } from 'react';
import { DAYS, SCHEMES, SHOP } from '../game/content';
import { dayConfig, type Action, type GameState } from '../game/engine';
import { Icon } from './Icon';
export function ScriptApp({ game, open, total }: { game: GameState; open: (id: string) => void; total: number }) {
 const day = dayConfig(game.day);
 return <div className="script-app"><div className="memo-top"><span>{t("INTERNAL MEMO")}</span><span>{t("NO. {0}", [String(game.day).padStart(3, '0')])}</span></div><h2>{t("今天，也别被开除。")}</h2><p className="memo-sub">{t(day.subtitle)}</p><div className="memo-quote">{t("“我不想听过程，我只想看数字。”")}<small>{t("— 你的老板，每一天")}</small></div><div className="memo-quota"><span>{t("DAY {0} · 今日目标", [String(game.day).padStart(2, '0')])}</span><strong>${t(day.quota.toLocaleString(languageTags[getLocale()]))}</strong><div><i style={{ width: `${Math.min(100, total / day.quota * 100)}%` }}/></div><small>{t("当前团队业绩 ${0} / ${1}", [total.toLocaleString(languageTags[getLocale()]), day.quota.toLocaleString(languageTags[getLocale()])])}</small></div><ol className="steps"><li><b>01</b><div><strong>{t("接听电话")}</strong><p>{t("等待来电，点击绿色接听按钮。")}</p></div></li><li><b>02</b><div><strong>{t("读懂对方，建立信任")}</strong><p>{t("根据来电者的性格选择回应。完成三次合适的回应后取得编号。")}</p></div></li><li><b>03</b><div><strong>{t("打开工具，完成任务")}</strong><p>{t("把编号填入对应应用。收入自动计入每日业绩。")}</p></div></li></ol><button className="blue full" onClick={() => open('phone')}><Icon name="phone" size={17}/>{t("打开工作电话")}<Icon name="right" size={17}/></button><p className="footnote">{t(day.brief)}</p></div>;
}
export function ShopApp({ game, dispatch }: { game: GameState; dispatch: (a: Action) => void }) {
 const [category, setCategory] = useState('all');
 const owned = (id: string) => { const item = SHOP.find(i => i.id === id)!; return !item.repeatable && (game.upgrades.includes(id) || (game.inventory?.[id] || 0) > 0 || !!game.deliveries?.some(d => d.item === id)); };
 return <div className="shop-app"><div className="shop-header"><h2>{t("scamazon")}<span>{t("MARKET")}</span><i/></h2><div>{t("你的钱包")}<strong>${t(game.balance.toLocaleString(languageTags[getLocale()]))}</strong></div></div><nav className="shop-tabs">{[['all', '全部商品'], ['business', '商业应用'], ['software', '游戏与软件'], ['goods', '实物商品']].map(([id, name]) => <button key={id} className={category === id ? 'active' : ''} onClick={() => setCategory(id)}>{t(name)}</button>)}</nav><div className="shop-banner"><span>{t("把钱花在刀刃上。")}<br/><strong>{t("或者一盆植物上。")}</strong></span><Icon name="shop" size={52}/></div><div className="shop-grid">{SHOP.filter(p => category === 'all' || p.category === category).map((p, i) => <article key={p.id}><div className={`product-art color-${i % 4}`}><Icon name={p.icon} size={52}/>{owned(p.id) && <span>{t("已拥有")}</span>}</div><div className="product-detail"><h3>{p.name}</h3><small>{t(p.english)} · {t(p.delivery ? '实物配送' : '即时安装')}</small><p>{t(p.description)}</p><footer><b>${t(p.price.toLocaleString(languageTags[getLocale()]))}</b><button className="yellow" disabled={owned(p.id) || game.balance < p.price || game.phase !== 'playing'} onClick={() => dispatch({ type: 'buy', id: p.id })}>{t(owned(p.id) ? '已拥有 / 已下单'  : game.balance < p.price ? `还差 $${p.price - game.balance}` : '购买')}</button></footer></div></article>)}</div></div>;
}
export function MalwareApp({ game, dispatch }: { game: GameState; dispatch: (a: Action) => void }) {
 const [scan, setScan] = useState(false);
 const labels: Record<string, string[]> = { fire: ['切断危险电器', '压制明火', '通风检查'], virus: ['隔离可疑进程', '删除病毒文件', '恢复系统服务'], power: ['断开过载线路', '重置断路器', '恢复供电'], raid: ['整理散落文件', '隐藏摸鱼窗口', '恢复办公室秩序'] };
 return <div className="malware-app"><Icon name={game.event ? 'warning' : 'shield'} size={70}/><h2>{t(game.event ? '你的工作站需要处理' : '你的电脑很安全。大概。')}</h2><p>{t(game.event ? '完成三个步骤，让一切回到正轨。' : 'Malwarebits 正在默默保护你最重要的资产：饭碗。')}</p><div className="scan-status"><span>{t("实时防护")}</span><b>{t(game.upgrades.includes('antivirus') ? 'PRO 已开启' : '基础版')}</b></div><div className="scan-status"><span>{t("当前威胁")}</span><b className={game.event ? 'danger-text' : ''}>{t(game.event ? '发现 1 项' : '0 项')}</b></div>{game.event ? <div className="fix-steps">{labels[game.event].map((s, i) => <button className={i < game.eventSteps ? 'fixed' : i === game.eventSteps ? 'blue' : ''} key={s} disabled={i !== game.eventSteps} onClick={() => dispatch({ type: 'fix' })}><span>{t(i < game.eventSteps ? '✓' : `0${i + 1}`)}</span>{t(s)}<Icon name="right" size={16}/></button>)}</div> : <><button className="blue full" onClick={() => setScan(true)}><Icon name="search" size={16}/>{t("扫描工作站")}</button>{scan && <p className="success-text">{t("扫描完成：所有模拟进程正常。")}</p>}</>}</div>;
}
export function PaintApp() {
 const canvas = useRef<HTMLCanvasElement>(null); const [color, setColor] = useState('#263e43'); const [size, setSize] = useState(5); const painting = useRef(false);
 const draw = (e: PointerEvent<HTMLCanvasElement>) => { if (!painting.current) return; const c = canvas.current!, r = c.getBoundingClientRect(), ctx = c.getContext('2d')!; ctx.strokeStyle = color; ctx.lineWidth = size; ctx.lineCap = 'round'; ctx.lineTo((e.clientX - r.left) * c.width / r.width, (e.clientY - r.top) * c.height / r.height); ctx.stroke(); };
 return <div className="paint-app"><div className="paint-tools">{['#263e43', '#ed6b5c', '#e4b348', '#60886c', '#5686ba', '#9d6cab', '#ffffff'].map(c => <button key={c} aria-label={t(`画笔颜色 ${c}`)} style={{ background: c }} className={color === c ? 'selected' : ''} onClick={() => setColor(c)}/>)}<input aria-label={t("画笔粗细")} type="range" min="2" max="24" value={size} onChange={e => setSize(+e.target.value)}/><button className="paint-clear" onClick={() => canvas.current?.getContext('2d')?.clearRect(0, 0, 800, 500)}>{t("清空")}</button></div><canvas ref={canvas} width={800} height={500} aria-label={t("画布")} onPointerDown={e => { painting.current = true; e.currentTarget.setPointerCapture(e.pointerId); const r = e.currentTarget.getBoundingClientRect(), ctx = e.currentTarget.getContext('2d')!; ctx.beginPath(); ctx.moveTo((e.clientX - r.left) * 800 / r.width, (e.clientY - r.top) * 500 / r.height); draw(e); }} onPointerMove={draw} onPointerUp={() => { painting.current = false; }} onPointerCancel={() => { painting.current = false; }}/><footer>{t("老板看不懂艺术，但他看得懂业绩。")}<button onClick={() => { const a = document.createElement('a'); a.href = canvas.current!.toDataURL(); a.download = 'kolkata-masterpiece.png'; a.click(); }}><Icon name="download" size={16}/>{t("保存作品")}</button></footer></div>;
}
export function CookieApp() {
 const [count, setCount] = useState(0), [power, setPower] = useState(1);
 return <div className="cookie-app"><small>{t("METEOR COOKIE")}</small><h2>{t(count.toLocaleString(languageTags[getLocale()]))}<span>{t("块宇宙饼干")}</span></h2><button className="big-cookie" aria-label={t("制作饼干")} onClick={() => setCount(count + power)}><Icon name="cookie" size={145}/></button><p>{t("每次点击 +{0} · 饼干不计入工作业绩", [power])}</p><button className="yellow" disabled={count < power * 20} onClick={() => { setCount(count - power * 20); setPower(power + 1); }}>{t("升级点击力 · {0} 饼干", [power * 20])}</button><small>{t("THIS IS DEFINITELY PRODUCTIVE.")}</small></div>;
}
export function CasinoApp({ game, dispatch }: { game: GameState; dispatch: (a: Action) => void }) { const [bet, setBet] = useState(10), [spinning, setSpinning] = useState(false); const spin = () => { if (spinning) return; setSpinning(true); dispatch({ type: 'gamble', bet }); setTimeout(() => setSpinning(false), 900); }; return <div className="casino-app"><h2>{t("rainbit")}<span>{t("THE ORIGINAL OFFICE CASINO")}</span></h2><div className="casino-balance">{t("BALANCE ")}<strong>${t(game.balance.toLocaleString(languageTags[getLocale()]))}</strong></div><div className={`slot-machine ${spinning ? 'spinning' : ''}`}><span>★</span><span>$</span><span>7</span></div><p>{t("赢了是眼光，输了是上班。")}</p><label>{t("投入游戏币")}<select value={bet} onChange={e => setBet(+e.target.value)}><option value={10}>$10</option><option value={25}>$25</option><option value={50}>$50</option><option value={100}>$100</option></select></label><button className="yellow full" disabled={spinning || game.balance < bet || game.phase !== 'playing'} onClick={spin}>{t(spinning ? '转动中…' : 'SPIN TO WIN')}</button><small>{t("仅限虚构游戏币 · 无充值、提现 · 胜率 35%，中奖返还 2 倍投入")}</small><p className="casino-result" role="status">{t(game.notice.startsWith('Rainbit') ? game.notice : '娱乐收益不计入今日业绩。')}</p></div>; }
export function BrowserApp() {
 const [tab, setTab] = useState('research');
 const links = [{ name: 'Steam 商店 · 原版游戏', url: 'https://store.steampowered.com/app/4954910/', note: '官方介绍、20 张截图、发布动态' }, { name: 'Jatater Worldwide', url: 'https://jataterworldwide.com/scam-with-your-friends/', note: '开发者官网与媒体资料包' }, { name: '官方玩法预告片', url: 'https://www.youtube.com/watch?v=e4BhBUryVFY', note: 'JakeHub · 1 分 49 秒' }, { name: 'We became Pro Scammers', url: 'https://www.youtube.com/watch?v=siFj51d0XbM', note: 'Rybolt · 42 分钟合作试玩' }, { name: 'Scamming Innocent People With My Friends!', url: 'https://www.youtube.com/watch?v=R92koVQGxK4', note: 'ShadesOfNate · 59 分钟试玩' }, { name: 'We Ran a SCAM Call Center', url: 'https://www.youtube.com/watch?v=-NIxPr-dNFw', note: 'More Griddles · 32 分钟试玩' }];
 return <div className="browser-app"><div className="browser-address"><Icon name="lock" size={13}/>{t("kolkata://{0}", [tab])}</div><nav><button className={tab === 'research' ? 'selected' : ''} onClick={() => setTab('research')}>{t("资料档案")}</button><button className={tab === 'levels' ? 'selected' : ''} onClick={() => setTab('levels')}>{t("工作周计划")}</button></nav>{tab === 'research' ? <div className="research-page"><small>{t("THE RESEARCH DESK")}</small><h2>{t("公开资料，")}<br/>{t("与我们的游戏设计。")}</h2><p>{t("此网页是非官方重制实验。官方素材作为研究参考；当前人物、美术、七日关卡和对话由网页版本重新实现。")}</p>{links.map(l => <a key={l.url} href={l.url} target="_blank" rel="noreferrer"><Icon name="browser" size={18}/><span><b>{t(l.name)}</b><small>{t(l.note)}</small></span><Icon name="right" size={16}/></a>)}</div> : <div className="level-list"><p>{t("以下七日编排为网页扩展设计，非已确认的原版关卡表。")}</p>{DAYS.map((d, i) => <article key={d.name}><b>0{t(i + 1)}</b><div><h3>{t(d.name)}</h3><p>{t(d.brief)}</p><small>{t("QUOTA ${0} · {1} MIN · ", [d.quota, d.seconds / 60])}{Object.values(SCHEMES).filter(s => s.day === i + 1).map(s => s.title).join(' / ') || '终极考核'}</small></div></article>)}</div>}</div>;
}
